Repository ovotech/comms-aws, pull requests merged in 2023-12, with the labels that each got.

#851 Update auth, s3, sdk-core to 2.21.38
  build.sbt
Labels: ovo-scala-steward, patch-update

#852 Update auth, s3, sdk-core to 2.21.43
  build.sbt
Labels: ovo-scala-steward, patch-update

#854 :wrench: Onboard Scala Steward
  .github/workflows/scala-steward.yml
Labels: kaluza-scala-caretakers

#857 Update sbt-header to 5.6.5 in master
  project/plugins.sbt
Labels: sbt-plugin-update, commit-count:1, early-semver-patch, semver-spec-patch

#861 Update scala-library to 2.13.12 in master
  build.sbt
Labels: commit-count:1, library-update, early-semver-patch, semver-spec-patch

#859 Update log4j-api, log4j-slf4j-impl to 2.22.1 in master
  build.sbt
Labels: commit-count:1, library-update, early-semver-patch, semver-spec-patch

#862 Update scala-xml to 2.2.0 in master
  build.sbt
Labels: commit-count:1, library-update, semver-spec-minor, early-semver-minor, version-scheme:early-semver

#867 Update slf4j-api to 1.7.36 in master
  build.sbt
Labels: commit-count:1, library-update, early-semver-patch, semver-spec-patch

#865 Update scalatest to 3.2.17 in master
  build.sbt
Labels: commit-count:1, library-update, early-semver-patch, semver-spec-patch

#863 Update sbt to 1.9.8 in master
  project/build.properties
Labels: commit-count:1, library-update, early-semver-patch, semver-spec-patch, version-scheme:early-semver

#868 Update auth, s3, sdk-core to 2.21.46 in master
  build.sbt
Labels: commit-count:1, library-update, early-semver-patch, semver-spec-patch

#869 Update sbt-header to 5.10.0 in master
  project/plugins.sbt
Labels: sbt-plugin-update, commit-count:1, semver-spec-minor, early-semver-minor

#860 Update scala-library to 2.12.18 in master
  build.sbt
Labels: commit-count:1, library-update, early-semver-patch, semver-spec-patch

#871 Update auth, s3, sdk-core to 2.22.8 in master
  build.sbt
Labels: commit-count:1, library-update, semver-spec-minor, early-semver-minor

#872 Update auth, s3, sdk-core to 2.22.9 in master
  build.sbt
Labels: commit-count:1, library-update, early-semver-patch, semver-spec-patch
